### ISSUE TITLE
can't change admin password in the docker-composed app

### ISSUE THREAD

**Issue by leipreachan** [mikecao/umami#164]
1. ubuntu 16.04 (LTS)
2. docker-compose up:
```
db_1     | CREATE INDEX                                                                                                                                                                             
db_1     | CREATE INDEX                                                                                
db_1     | CREATE INDEX                                        
db_1     | INSERT 0 1                                                        
db_1     |                                                   
db_1     |                                            
db_1     | 2020-09-15 08:12:21.619 UTC [34] LOG:  received fast shutdown request
db_1     | waiting for server to shut down....2020-09-15 08:12:21.627 UTC [34] LOG:  aborting any active transactions
db_1     | 2020-09-15 08:12:21.630 UTC [34] LOG:  background worker "logical replication launcher" (PID 41) exited with exit code 1
db_1     | 2020-09-15 08:12:21.630 UTC [36] LOG:  shutting down                 
db_1     | 2020-09-15 08:12:21.693 UTC [34] LOG:  database system is shut down
db_1     |  done                                           
db_1     | server stopped                                       
db_1     |                        
db_1     | PostgreSQL init process complete; ready for start up.                               
db_1     |                           
db_1     | 2020-09-15 08:12:21.735 UTC [1] LOG:  starting PostgreSQL 12.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.3.0) 9.3.0, 64-bit                                
db_1     | 2020-09-15 08:12:21.735 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432               
db_1     | 2020-09-15 08:12:21.736 UTC [1] LOG:  listening on IPv6 address "::", port 5432                
db_1     | 2020-09-15 08:12:21.751 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1     | 2020-09-15 08:12:21.781 UTC [47] LOG:  database system was shut down at 2020-09-15 08:12:21 UTC
db_1     | 2020-09-15 08:12:21.790 UTC [1] LOG:  database system is ready to accept connections
........
db_1     |                                                                                                            
db_1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1     |                                                                                                            
db_1     | 2020-09-15 08:47:15.498 UTC [1] LOG:  starting PostgreSQL 12.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.3.0) 9.3.0, 64-bit
db_1     | 2020-09-15 08:47:15.499 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432                       
db_1     | 2020-09-15 08:47:15.499 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1     | 2020-09-15 08:47:15.508 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1     | 2020-09-15 08:47:15.556 UTC [20] LOG:  database system was shut down at 2020-09-15 08:13:47 UTC
db_1     | 2020-09-15 08:47:15.593 UTC [1] LOG:  database system is ready to accept connections
umami_1  |                                                                       
umami_1  | > umami@0.33.0 start /app                                               
umami_1  | > next start                                                                  
umami_1  |                                                                                       
umami_1  | ready - started server on http://localhost:3000    
```
.....
3. Log in as admin / umami to the app (localhost:3000) 
4. Try to change your password
... I receive 401 HTTP Error, no new entries in log files

Any ideas what can go wrong?
Thanks

**Comment by kai-oswald** [comment]
Same on the non-docker version.
Also deleting users gives 401 Unauthorized too.

I tried pasting the jwt on https://jwt.io to see its values and it says that the signature is invalid.

**Comment by leipreachan** [comment]
Yep, deleting doesn't work, too.
Is it possible that the DB image is RO?

**Comment by kai-oswald** [comment]
Changing the password of non-admin users works tho.

**Comment by mikecao** [comment]
I just pushed out a fix. Try pulling the latest.

**Comment by leipreachan** [comment]
@mikecao thanks, it works now.

cheers

**Comment by kai-oswald** [comment]
Accounts still cannot be deleted.

**Comment by mikecao** [comment]
@kai-oswald Yea I missed that one. Should be fixed now.

**Comment by SuLingGG** [comment]
Changing the password of non-admin users still not work at  1.4.0...

**Comment by mikecao** [comment]
@SuLingGG what error do you get? It works for me.

**Comment by SuLingGG** [comment]
> @SuLingGG what error do you get? It works for me.

401 Unauthorized, Change browser or force refresh have no effect, too. But admin can change anyone's password.

**Comment by mikecao** [comment]
@SuLingGG  Oh you mean non-admin changing their own password. That looks like a bug. Can you create a new issue?

**Comment by SuLingGG** [comment]
> @SuLingGG Oh you mean non-admin changing their own password. That looks like a bug. Can you create a new issue?

Okay, Issue created at <https://github.com/mikecao/umami/issues/351>
